### ISSUE TITLE
Website?

### ISSUE THREAD

**Issue by IainNZ** [JuliaStats/Roadmap.jl#13]
e.g. juliastats.org

Purpose would be a guide to the various parts of the JuliaStats empire

**Comment by johnmyleswhite** [comment]
This would be great to have.

**Comment by lindahua** [comment]
+1 for a website.

**Comment by IainNZ** [comment]
I'm thinking of making a base website for all orgs to use and customize as they need, motivated by the fact Miles pretty much just copied the JuliaOpt site for JuliaDiff, which is actually based on my personal website. So - might as well do it right! Not sure on the ETA on that though, just thought I'd let you know in case someone was thinking about making it soon.

**Comment by WestleyArgentum** [comment]
+100 That would be awesome!

**Comment by lindahua** [comment]
I have registered the juliastats.org domain name, and created JuliaStats.github.io for webpage development. The efforts of building the website is underway.

**Comment by lindahua** [comment]
I just established a website: http://juliastats.org

**Comment by johnmyleswhite** [comment]
This looks great. Well done, Dahua!

**Comment by lindahua** [comment]
Use http://juliastats.github.io/ for now. 

The redirection from http://juliastats.org seems to result in some weird behavior.

**Comment by IainNZ** [comment]
:+1: awesome!

**Comment by IainNZ** [comment]
(just need a logo now :D)
