### ISSUE TITLE
StatPlots.jl

### ISSUE THREAD

**Issue by tbreloff** [JuliaStats/Roadmap.jl#18]
I intend to split off some "statistical plotting recipes" from my Plots.jl package, as well as add more.  I think it makes a lot of sense to have these separate from the core plotting, and I also think it makes sense for these recipes to be part of JuliaStats, primarily because I want others to contribute common analysis tools.  See [corrplot](https://github.com/tbreloff/Plots.jl/blob/master/src/recipes.jl#L66-L111) and https://github.com/tbreloff/Plots.jl/issues/42 as an example of what might be included.

The main questions:
- Should StatPlots.jl be part of JuliaStats?
- Is that a good name for it?

Secondary: What should be included?  I'll start with a short list:
- Correlation plots
- QQ plots
- Density estimation overlays
- Regression residuals

**Comment by ahwillia** [comment]
Scatterplot matrices! https://gist.github.com/ahwillia/43c2cfb894f2bfec6760

Apologies if you've moved on from this idea. But I would be very interested in this.

**Comment by tbreloff** [comment]
I forgot about this issue... sorry.  The home for statistical recipes is now: https://github.com/JuliaPlots/PlotRecipes.jl.  Contributions welcome!
