### ISSUE TITLE
New JuliaStats logo?

### ISSUE THREAD

**Issue by ararslan** [JuliaStats/Roadmap.jl#22]
I think it would be nice if JuliaStats could have a distinguishing logo, just as JuliaDB and others do, rather than the same logo as JuliaLang. Here's my proposal, poorly made in the course of about 5 minutes in an MS Paint clone:

![untitled](https://cloud.githubusercontent.com/assets/6396159/15194627/9f254cea-1778-11e6-9ea3-efbd9d606ed3.png)

It's just the Julia dots with the normal distribution overlaid. Not super exciting but I figured that the normal distribution is pretty iconic and could work well in this scenario.

Thoughts? I'm certainly no graphic designer; this is just an idea. (Though if people do like this, I'd request that someone with decent image software make one that looks less sloppy, especially if we need transparency.)

**Comment by nalimilan** [comment]
Good idea, but the curve should be more like a normal distribution, and we should have a SVG version.

**Comment by tbreloff** [comment]
Something like this might be cool too:

![tmp](https://cloud.githubusercontent.com/assets/933338/15196234/641ea026-1799-11e6-8924-82fa78ca9812.png)

**Comment by ararslan** [comment]
Fancy! :smile: I like it but I think it's less immediately recognizable as a derivative of the Julia logo. (Not sure whether that's actually a negative, just sayin'.)

**Comment by mschauer** [comment]
Isnt that a bit too much Freudian innuendo¿ ^^

**Comment by ararslan** [comment]
😖 Maybe to ameliorate that we could move the means of the red and purple distributions away from the center and decrease their variances a bit?

**Comment by tbreloff** [comment]
@mschauer I learned a lot about you today!

@ararslan Feel free to play with that bit of code and come up with something else!

**Comment by ararslan** [comment]
@tbreloff I actually can't seen to get Plots to work under 0.3, 0.4, or 0.5. But I'm fine with whatever, it was just a suggestion. 😄

**Comment by tbreloff** [comment]
@ararslan Do you mind opening a Plots issue or [chatting in gitter](https://gitter.im/tbreloff/Plots.jl) with more details?

**Comment by ararslan** [comment]
![figure_1](https://cloud.githubusercontent.com/assets/6396159/15233587/d9fe341c-185e-11e6-8049-43bfdf519712.png)

Modification of Tom's image.

**Comment by kmsquire** [comment]
I actually like @ararslan's original idea better.

**Comment by cstjean** [comment]
![screen shot 2016-05-13 at 09 08 42](https://cloud.githubusercontent.com/assets/8622776/15248860/6e402dde-18ea-11e6-9f5e-3b2f22c1d31b.png)

The colors are a bit too flashy...

**Comment by KristofferC** [comment]
Cool!

**Comment by andreasnoack** [comment]
I like this one. Maybe without the axes?

**Comment by mschauer** [comment]
Yes there should be noise.

**Comment by tbreloff** [comment]
I like it... similar to the one I made for [JuliaML](https://github.com/JuliaML)

**Comment by ararslan** [comment]
I like this one as well. But is it _too_ similar to Tom's image for JuliaML?

**Comment by ararslan** [comment]
Bump for this discussion. @cstjean's suggestion looks great to me but I agree with @andreasnoack that the axes should be removed.

**Comment by cstjean** [comment]
I made the axes transparent and cropped it manually. I couldn't figure out how to make the background transparent, but that could be done manually too.

![juliastats](https://cloud.githubusercontent.com/assets/8622776/16174888/de5ea7b6-35a6-11e6-93ee-277cabdbbdeb.png)

If anyone else wants to tweak it further:

``` julia
using Plots
plotly()
N = 2000
w = 0.3
al = 0.7
m = (:circle, 2.5, 0.4, stroke(0))
l = 2.5
scatter(randn(N)*w, randn(N)*w+2, color=:green, size=(200,200), legend=false, alpha=al, marker=m, grid=false, foreground_color=RGBA(0.0,0.0,0.0,0.0), xlims=(-l,l), ylims=(1-l, 1+l))
scatter!(randn(N)*w-1, randn(N)*w, color=:red, alpha=al, legend=false, marker=m)
scatter!(randn(N)*w+1, randn(N)*w, color=:purple, alpha=al, legend=false, marker=m)
```

**Comment by ararslan** [comment]
I don't know how much the transparent background actually matters; the JuliaMath logo's background is white, for example.

**Comment by ararslan** [comment]
![unknown](https://cloud.githubusercontent.com/assets/6396159/16790896/662c5178-486e-11e6-991f-cc31a86c9d00.png)

Modified @cstjean's to reduce the height so that the dot centers form an equilateral triangle and made the background transparent.

**Comment by quinnj** [comment]
+1
